#Docker build fails


# version: '2'
# services:
#   db:
#     image: mysql:8
#     restart: always
#     ports:
#       - "3306:3306"
#     environment:
#       - MYSQL_DATABASE='hotel_reservations_test'
#       - MYSQL_USER='root'
#       - MYSQL_ROOT_PASSWORD='rootpassword'
#       - MYSQL_HOST=''
#     volumes:
#       - ./db:/var/lib/mysql
#     expose:
#       - "3306"

#   web:
#     build: .
#     command: python manage.py runserver 0.0.0.0:8000
#     restart: always
#     ports:
#       - "8000:8000"
#     volumes:
#       - .:/hotelreservationsapp
#     depends_on:
#       - db