version: '3'
services:
  db:
    image: mysql:8
    restart: always
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=hotel_reservations_test
      - MYSQL_USER=my_user
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_PASSWORD=my_password
    command: --authentication-policy=mysql_native_password
    healthcheck:
      test: "mysqladmin ping -h localhost"
      interval: 20s
      timeout: 1s
      retries: 10
      start_period: 20s

  web:
    build:
      context: .
      dockerfile: Dockerfile
    #command: /bin/bash -c "/code/scripts/runserver.sh"
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
