# Generated by Django 4.1 on 2022-08-24 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='client_fullname',
            field=models.CharField(default='', max_length=60),
        ),
    ]
